# This Dockerfile are use for local development
FROM golang:1.20.5-alpine3.18

WORKDIR /go/src/app

# Add steps to setup private repo like as Dockerfile if working with private repo

ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin
ENV CGO_ENABLED=0

COPY . .

RUN go mod tidy
RUN go install github.com/mitranim/gow@latest

EXPOSE $PORT
