name: ci
on: 
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  
jobs:
  golangci-lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
